/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sebas
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Sistema sistema;
    private File archivoEquipos;
    private File archivoReportes;
    private AgregarEquipos ventanaAgregar;
    private AgregarReporte ventanaAgregarReporte;
    private VentanaInformacionReportes ventanaInformacionReportes;
    private ventanaReportesPorTramo ventanaReportesPorTramo;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() throws FileNotFoundException, IOException {
        sistema = new SistemaImpl();
        leerArchivoEquipos();
        leerArchivoReportes();
        initComponents();
        ventanaAgregar = new AgregarEquipos(sistema);
        ventanaAgregarReporte = new AgregarReporte(sistema);
        ventanaInformacionReportes = new VentanaInformacionReportes(sistema);
        ventanaReportesPorTramo = new ventanaReportesPorTramo(sistema);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        botonInfoReportes = new javax.swing.JButton();
        botonReportesPorTramo = new javax.swing.JButton();
        botonReportesDiariosMaquinas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        nuevo = new javax.swing.JMenu();
        nuevoIngresarMaquinaria = new javax.swing.JMenuItem();
        nuevoIngresarReporte = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido al sistema de control de maquinarias");

        botonInfoReportes.setText("Ver reportes mensuales por equipo");
        botonInfoReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfoReportesActionPerformed(evt);
            }
        });

        botonReportesPorTramo.setText("Ver reportes por tramo");
        botonReportesPorTramo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportesPorTramoActionPerformed(evt);
            }
        });

        botonReportesDiariosMaquinas.setText("Ver reportes por dia Maquinas");

        nuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nuevo.setText("Nuevo");

        nuevoIngresarMaquinaria.setText("Nueva maquinaria");
        nuevoIngresarMaquinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoIngresarMaquinariaActionPerformed(evt);
            }
        });
        nuevo.add(nuevoIngresarMaquinaria);

        nuevoIngresarReporte.setText("Nuevo reporte");
        nuevoIngresarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoIngresarReporteActionPerformed(evt);
            }
        });
        nuevo.add(nuevoIngresarReporte);

        jMenuBar1.add(nuevo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botonReportesPorTramo)
                    .addComponent(botonInfoReportes)
                    .addComponent(botonReportesDiariosMaquinas)
                    .addComponent(jLabel1))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(botonInfoReportes)
                .addGap(18, 18, 18)
                .addComponent(botonReportesPorTramo)
                .addGap(18, 18, 18)
                .addComponent(botonReportesDiariosMaquinas)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoIngresarMaquinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoIngresarMaquinariaActionPerformed
        // TODO add your handling code here:
        ventanaAgregar.setVisible(true);
    }//GEN-LAST:event_nuevoIngresarMaquinariaActionPerformed

    private void nuevoIngresarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoIngresarReporteActionPerformed
        // TODO add your handling code here:
        ventanaAgregarReporte.setVisible(true);
    }//GEN-LAST:event_nuevoIngresarReporteActionPerformed

    private void botonInfoReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfoReportesActionPerformed
        // TODO add your handling code here:
        ventanaInformacionReportes.setVisible(true);
    }//GEN-LAST:event_botonInfoReportesActionPerformed

    private void botonReportesPorTramoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportesPorTramoActionPerformed
        // TODO add your handling code here:
        ventanaReportesPorTramo.setVisible(true);
    }//GEN-LAST:event_botonReportesPorTramoActionPerformed

    public void leerArchivoReportes() throws FileNotFoundException{
        archivoReportes = new File("reportes.txt");
        if (archivoReportes.exists()){
            Scanner scanner = new Scanner(archivoReportes);
            String tipo,codigoEquipo,horastrabajadas,horasSB,cantPetroleo,horasPanne,horometroFinal,horometroInicial,fecha;
            String linea = "";
            while(scanner.hasNextLine()){
                linea = scanner.nextLine();
                if(!linea.equals("")){
                    tipo = linea.split(",")[0];
                    codigoEquipo = linea.split(",")[1];
                    horastrabajadas = linea.split(",")[2];
                    horasSB = linea.split(",")[3];
                    cantPetroleo = linea.split(",")[4];
                    horasPanne = linea.split(",")[5];
                    horometroFinal = linea.split(",")[6];
                    horometroInicial = linea.split(",")[7];
                    fecha = linea.split(",")[8];
                    if ("C".equals(tipo)){
                        String numeroVueltas = linea.split(",")[9];
                        sistema.ingresarReporteCamion(Double.parseDouble(horastrabajadas), Double.parseDouble(horasSB), Integer.parseInt(cantPetroleo), Double.parseDouble(horometroFinal), Double.parseDouble(horometroInicial), codigoEquipo, Double.parseDouble(horasPanne), fecha, Integer.parseInt(numeroVueltas));
                    }
                    if ("M".equals(tipo)){
                        sistema.ingresarReporteMaquina(Double.parseDouble(horastrabajadas), Double.parseDouble(horasSB), Integer.parseInt(cantPetroleo), Double.parseDouble(horometroFinal), Double.parseDouble(horometroInicial), codigoEquipo, Double.parseDouble(horasPanne), fecha);
                    }
                }
            }
        }
    }
    
    public void leerArchivoEquipos() throws FileNotFoundException{
        archivoEquipos = new File("equipos.txt");
        if(archivoEquipos.exists()){
            Scanner scanner = new Scanner(archivoEquipos);
            String tipo,codigo;
            String Horometro;
            String linea = "";
            while (scanner.hasNextLine()){
                linea = scanner.nextLine();
                if(!linea.equals("")){
                    tipo = linea.split(",")[0];
                    codigo = linea.split(",")[1];
                    Horometro = linea.split(",")[2];
                    if (tipo.equals("C")){
                        String Toneladas = linea.split(",")[3];
                        sistema.ingresarCamion(codigo, Integer.parseInt(Toneladas), Double.parseDouble(Horometro));
                    }
                    else{
                        sistema.ingresarMaquina(codigo, Double.parseDouble(Horometro));
                    }
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaPrincipal().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInfoReportes;
    private javax.swing.JButton botonReportesDiariosMaquinas;
    private javax.swing.JButton botonReportesPorTramo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu nuevo;
    private javax.swing.JMenuItem nuevoIngresarMaquinaria;
    private javax.swing.JMenuItem nuevoIngresarReporte;
    // End of variables declaration//GEN-END:variables

}
